import {
  DEFAULT_PARAMS,
  type EffectParams,
  type FilterMode,
  type Preset,
} from "./types";

/**
 * Preset library:
 * - generic digital filters live under the Filters menu
 * - very small / phone-era profiles live under Camera 2
 * - identifiable compact-camera families remain directly visible
 *
 * These are character profiles, not exact color-science recreations of a
 * particular production unit.
 */
function preset(
  id: string,
  name: string,
  note: string,
  params: Partial<EffectParams>,
  filter: FilterMode = "none",
): Preset {
  return {
    id,
    name,
    note,
    params: { ...DEFAULT_PARAMS, ...params },
    filter,
  };
}

export const PRESETS: Preset[] = [
  preset("none", "Original", "No processing applied.", {}),

  // Reference-style generic filters.
  preset(
    "jpeg",
    "JPEG",
    "Low-quality digital JPEG: block structure, chroma bleed and crisp camera sharpening.",
    {
      grain: 0.16,
      jpeg: 0.9,
      colorShift: 0.22,
      vignette: 0.06,
      softness: 0.05,
      sharpen: 0.6,
      aberration: 0.06,
    },
  ),
  preset(
    "bw",
    "B&W",
    "Monochrome digital conversion with a little extra tonal separation.",
    {
      grain: 0.08,
      jpeg: 0.08,
      contrast: 0.12,
      sharpen: 0.18,
    },
    "bw",
  ),
  preset(
    "sepia",
    "Sepia",
    "Warm brown monochrome conversion with restrained digital texture.",
    {
      grain: 0.08,
      jpeg: 0.08,
      contrast: 0.08,
      sharpen: 0.12,
    },
    "sepia",
  ),
  preset(
    "negative",
    "Negative",
    "Digital negative/inverted colour treatment.",
    {
      grain: 0.04,
      jpeg: 0.06,
    },
    "negative",
  ),
  preset(
    "warm-filter",
    "Warm",
    "Simple warm colour filter without film grain or fake vintage toning.",
    { contrast: 0.08, saturation: 0.05 },
    "warm",
  ),
  preset(
    "cool-filter",
    "Cool",
    "Simple cool colour filter with a clean digital balance.",
    { contrast: 0.06, saturation: 0.04 },
    "cool",
  ),
  preset(
    "high-contrast",
    "High Contrast",
    "Punchy digital contrast with clipped highlights and deeper blacks.",
    { contrast: 0.08, saturation: 0.08, sharpen: 0.2 },
    "high-contrast",
  ),

  // Non-filter reference looks.
  preset(
    "collage",
    "Collage",
    "Soft consumer-digital base with slightly lifted colour and gentle texture.",
    {
      grain: 0.24,
      jpeg: 0.28,
      colorShift: 0.42,
      vignette: 0.12,
      softness: 0.18,
      sharpen: 0.3,
      bloom: 0.1,
      aberration: 0.1,
      fade: 0.08,
      contrast: 0.04,
      saturation: 0.16,
      temperature: 0.08,
    },
  ),
  preset(
    "blur-pixelate",
    "Blur/Pixelate",
    "Small-sensor softness with obvious digital blocking and reduced detail.",
    {
      grain: 0.32,
      jpeg: 0.74,
      colorShift: 0.38,
      vignette: 0.12,
      softness: 0.58,
      sharpen: 0.1,
      aberration: 0.16,
      fade: 0.14,
      contrast: 0.02,
      saturation: -0.04,
    },
  ),
  preset(
    "ccd",
    "CCD",
    "Classic CCD compact character: lively channels, crosstalk, crisp edges and a little bloom.",
    {
      grain: 0.24,
      jpeg: 0.28,
      colorShift: 0.78,
      vignette: 0.2,
      softness: 0.1,
      sharpen: 0.7,
      bloom: 0.14,
      aberration: 0.16,
      fade: 0.06,
      temperature: 0.06,
      contrast: 0.24,
      saturation: 0.3,
    },
  ),

  // Camera 2 group.
  preset(
    "nokia",
    "Nokia",
    "Early Nokia camera-phone character: tiny sensor, soft detail and noisy shadows.",
    {
      grain: 0.72,
      jpeg: 0.72,
      colorShift: 0.5,
      vignette: 0.22,
      softness: 0.5,
      sharpen: 0.28,
      aberration: 0.28,
      fade: 0.22,
      temperature: -0.06,
      exposure: -0.06,
      contrast: 0.08,
      saturation: -0.14,
    },
  ),
  preset(
    "quarter-inch",
    '1/4"',
    "Tiny 1/4-inch-class sensor: weak dynamic range, softness and noisy shadow detail.",
    {
      grain: 0.64,
      jpeg: 0.58,
      colorShift: 0.48,
      vignette: 0.18,
      softness: 0.44,
      sharpen: 0.34,
      bloom: 0.08,
      aberration: 0.26,
      fade: 0.2,
      temperature: -0.04,
      exposure: -0.04,
      contrast: 0.14,
      saturation: -0.08,
    },
  ),
  preset(
    "iphone-3gs",
    "iPhone3gs",
    "Early smartphone camera: soft detail, limited dynamic range and crunchy JPEG colour.",
    {
      grain: 0.52,
      jpeg: 0.5,
      colorShift: 0.34,
      vignette: 0.12,
      softness: 0.38,
      sharpen: 0.5,
      bloom: 0.08,
      aberration: 0.18,
      fade: 0.14,
      temperature: 0.04,
      exposure: 0.02,
      contrast: 0.14,
      saturation: 0.08,
    },
  ),

  // Identifiable compact-camera families.
  preset(
    "sony-cybershot",
    "Sony Cyber-shot",
    "Compact CCD character: cool daylight balance, crisp edges and moderate JPEG texture.",
    {
      grain: 0.22,
      jpeg: 0.24,
      colorShift: 0.5,
      vignette: 0.16,
      softness: 0.08,
      sharpen: 0.72,
      bloom: 0.1,
      aberration: 0.13,
      fade: 0.06,
      temperature: -0.18,
      contrast: 0.22,
      saturation: 0.16,
    },
  ),
  preset(
    "canon-powershot",
    "Canon PowerShot",
    "Consumer compact look with warm skin bias, punchy contrast and clear in-camera sharpening.",
    {
      grain: 0.25,
      jpeg: 0.22,
      colorShift: 0.42,
      vignette: 0.18,
      softness: 0.09,
      sharpen: 0.62,
      bloom: 0.12,
      aberration: 0.11,
      fade: 0.05,
      temperature: 0.22,
      exposure: 0.04,
      contrast: 0.28,
      saturation: 0.22,
    },
  ),
  preset(
    "canon-ixus",
    "Canon Digital IXUS",
    "Small metal-pocket compact character with direct flash, clean daylight and clipped highlights.",
    {
      grain: 0.2,
      jpeg: 0.28,
      colorShift: 0.36,
      vignette: 0.34,
      softness: 0.06,
      sharpen: 0.64,
      bloom: 0.26,
      aberration: 0.14,
      flash: 0.58,
      temperature: 0.08,
      exposure: 0.06,
      contrast: 0.3,
      saturation: 0.14,
    },
  ),
  preset(
    "nikon-coolpix",
    "Nikon COOLPIX",
    "Cool-to-neutral CCD rendering with deep shadows and strong consumer-camera sharpening.",
    {
      grain: 0.28,
      jpeg: 0.3,
      colorShift: 0.48,
      vignette: 0.2,
      softness: 0.12,
      sharpen: 0.68,
      bloom: 0.08,
      aberration: 0.16,
      fade: 0.04,
      temperature: -0.14,
      contrast: 0.32,
      saturation: 0.08,
    },
  ),
  preset(
    "fujifilm-finepix",
    "Fujifilm FinePix",
    "Soft CCD response with lively greens, blue daylight and gentle highlight glow.",
    {
      grain: 0.24,
      jpeg: 0.2,
      colorShift: 0.6,
      vignette: 0.12,
      softness: 0.16,
      sharpen: 0.4,
      bloom: 0.2,
      aberration: 0.12,
      fade: 0.08,
      temperature: 0.04,
      exposure: 0.03,
      contrast: 0.12,
      saturation: 0.3,
    },
  ),
  preset(
    "casio-exilim",
    "Casio Exilim",
    "Bright pocket-camera processing with saturated colour and pronounced edge sharpening.",
    {
      grain: 0.14,
      jpeg: 0.18,
      colorShift: 0.34,
      vignette: 0.1,
      softness: 0.05,
      sharpen: 0.78,
      bloom: 0.12,
      aberration: 0.1,
      temperature: 0.12,
      exposure: 0.08,
      contrast: 0.2,
      saturation: 0.3,
    },
  ),
  preset(
    "olympus-camedia",
    "Olympus CAMEDIA",
    "Warm consumer CCD with soft corners, greenish shadow drift and visible JPEG texture.",
    {
      grain: 0.3,
      jpeg: 0.38,
      colorShift: 0.62,
      vignette: 0.24,
      softness: 0.18,
      sharpen: 0.5,
      bloom: 0.14,
      aberration: 0.2,
      fade: 0.1,
      temperature: 0.18,
      exposure: 0.02,
      contrast: 0.2,
      saturation: 0.16,
    },
  ),
  preset(
    "panasonic-lumix",
    "Panasonic Lumix",
    "Cooler compact rendering with high micro-contrast and a clean digital finish.",
    {
      grain: 0.18,
      jpeg: 0.22,
      colorShift: 0.4,
      vignette: 0.14,
      softness: 0.07,
      sharpen: 0.84,
      bloom: 0.07,
      aberration: 0.11,
      temperature: -0.24,
      contrast: 0.3,
      saturation: 0.12,
    },
  ),
  preset(
    "kodak-easyshare",
    "Kodak EasyShare",
    "Warm consumer colour, mild highlight bloom and familiar JPEG crunch.",
    {
      grain: 0.3,
      jpeg: 0.36,
      colorShift: 0.54,
      vignette: 0.2,
      softness: 0.15,
      sharpen: 0.46,
      bloom: 0.22,
      aberration: 0.15,
      fade: 0.14,
      temperature: 0.3,
      exposure: 0.05,
      contrast: 0.16,
      saturation: 0.2,
    },
  ),
  preset(
    "pentax-optio",
    "Pentax Optio",
    "Small-sensor compact look with soft detail, muddy blacks and imperfect white balance.",
    {
      grain: 0.34,
      jpeg: 0.44,
      colorShift: 0.58,
      vignette: 0.28,
      softness: 0.3,
      sharpen: 0.48,
      bloom: 0.12,
      aberration: 0.22,
      fade: 0.16,
      temperature: -0.06,
      contrast: 0.12,
      saturation: 0.04,
    },
  ),
  preset(
    "samsung-digimax",
    "Samsung Digimax",
    "Budget compact colour errors, chunky JPEG texture and visible small-sensor noise.",
    {
      grain: 0.42,
      jpeg: 0.56,
      colorShift: 0.74,
      vignette: 0.3,
      softness: 0.26,
      sharpen: 0.52,
      bloom: 0.1,
      aberration: 0.26,
      fade: 0.18,
      temperature: -0.12,
      contrast: 0.18,
      saturation: 0.08,
    },
  ),
  preset(
    "early-camera-phone",
    "Early Camera Phone",
    "Tiny-sensor mush: high shadow noise, weak dynamic range and heavy JPEG damage.",
    {
      grain: 0.78,
      jpeg: 0.66,
      colorShift: 0.52,
      vignette: 0.24,
      softness: 0.48,
      sharpen: 0.36,
      bloom: 0.05,
      aberration: 0.3,
      fade: 0.24,
      temperature: -0.08,
      exposure: -0.08,
      contrast: 0.16,
      saturation: -0.12,
    },
  ),
  preset(
    "night-flash-compact",
    "Night Flash Compact",
    "Direct-flash party snapshot: dark backgrounds, clipped near-field highlights and sensor noise.",
    {
      grain: 0.5,
      jpeg: 0.42,
      colorShift: 0.38,
      vignette: 0.52,
      softness: 0.1,
      sharpen: 0.74,
      bloom: 0.32,
      aberration: 0.2,
      flash: 0.9,
      temperature: -0.1,
      exposure: 0.1,
      contrast: 0.38,
      saturation: 0.02,
    },
  ),
];

export const PRESET_MAP: Record<string, Preset> = Object.fromEntries(
  PRESETS.map((p) => [p.id, p]),
);

export function paramsEqual(a: EffectParams, b: EffectParams): boolean {
  return (Object.keys(a) as (keyof EffectParams)[]).every(
    (k) => Math.abs(a[k] - b[k]) < 0.0005,
  );
}
