import { DEFAULT_PARAMS, type EffectParams, type Preset } from "./types";

/**
 * Preset library.
 *
 * Presets are pure data. To add one, append an entry below with any subset of
 * `EffectParams` - missing keys fall back to the neutral defaults. No renderer
 * change is required.
 */
function preset(id: string, name: string, note: string, params: Partial<EffectParams>): Preset {
  return { id, name, note, params: { ...DEFAULT_PARAMS, ...params } };
}

export const PRESETS: Preset[] = [
  preset("none", "Original", "No processing applied.", {}),
  preset("ccd-warm", "CCD Warm", "Warm 2004 compact, gentle noise, soft corners.", {
    grain: 0.3,
    jpeg: 0.26,
    colorShift: 0.55,
    vignette: 0.22,
    softness: 0.14,
    sharpen: 0.35,
    bloom: 0.12,
    aberration: 0.18,
    fade: 0.1,
    temperature: 0.34,
    exposure: 0.06,
    contrast: 0.16,
    saturation: 0.2,
  }),
  preset("pocket-flash", "Pocket Flash", "Hot on-camera flash, clipped skin, dark falloff.", {
    grain: 0.24,
    jpeg: 0.3,
    colorShift: 0.34,
    vignette: 0.42,
    softness: 0.08,
    sharpen: 0.5,
    bloom: 0.3,
    aberration: 0.14,
    flash: 0.72,
    temperature: -0.08,
    exposure: 0.1,
    contrast: 0.3,
    saturation: 0.05,
  }),
  preset("old-cmos", "Old CMOS", "Early phone sensor: flat colour, mushy detail, blocks.", {
    grain: 0.46,
    jpeg: 0.62,
    colorShift: 0.4,
    vignette: 0.26,
    softness: 0.34,
    sharpen: 0.62,
    bloom: 0.06,
    aberration: 0.26,
    fade: 0.22,
    temperature: -0.12,
    contrast: 0.08,
    saturation: -0.16,
  }),
  preset("night-compact", "Night Compact", "ISO 400 handheld: chroma noise, crushed shadows.", {
    grain: 0.82,
    jpeg: 0.44,
    colorShift: 0.5,
    vignette: 0.5,
    softness: 0.2,
    sharpen: 0.3,
    bloom: 0.34,
    aberration: 0.22,
    fade: 0.06,
    exposure: -0.14,
    contrast: 0.34,
    temperature: 0.16,
    saturation: -0.08,
  }),
  preset("soft-digital", "Soft Digital", "Clean, slightly soft, mild sensor character.", {
    grain: 0.16,
    jpeg: 0.14,
    colorShift: 0.24,
    vignette: 0.12,
    softness: 0.26,
    sharpen: 0.18,
    bloom: 0.18,
    aberration: 0.1,
    fade: 0.16,
    temperature: 0.1,
    exposure: 0.08,
    contrast: -0.06,
    saturation: 0.08,
  }),
  preset("harsh-flash", "Harsh Flash", "Party snapshot. Blown highlights, hard edges.", {
    grain: 0.34,
    jpeg: 0.4,
    colorShift: 0.3,
    vignette: 0.58,
    softness: 0.04,
    sharpen: 0.78,
    bloom: 0.42,
    aberration: 0.2,
    flash: 0.92,
    exposure: 0.16,
    contrast: 0.42,
    saturation: -0.1,
    temperature: -0.14,
  }),
  preset("cool-ccd", "Cool CCD", "Cyan-leaning daylight balance, crisp and cold.", {
    grain: 0.22,
    jpeg: 0.2,
    colorShift: 0.66,
    vignette: 0.2,
    softness: 0.08,
    sharpen: 0.44,
    bloom: 0.1,
    aberration: 0.16,
    fade: 0.12,
    temperature: -0.42,
    contrast: 0.2,
    saturation: 0.16,
  }),
  preset("late-2000s", "Late 2000s", "12MP era: over-sharpened, punchy, thin noise.", {
    grain: 0.2,
    jpeg: 0.34,
    colorShift: 0.3,
    vignette: 0.16,
    softness: 0.06,
    sharpen: 0.86,
    bloom: 0.08,
    aberration: 0.12,
    contrast: 0.28,
    saturation: 0.32,
    temperature: 0.08,
    exposure: 0.04,
  }),
  preset("cheap-compact", "Cheap Compact", "Supermarket camera: blocky, muddy, oddly green.", {
    grain: 0.5,
    jpeg: 0.86,
    colorShift: 0.74,
    vignette: 0.34,
    softness: 0.4,
    sharpen: 0.4,
    bloom: 0.12,
    aberration: 0.38,
    fade: 0.3,
    temperature: -0.2,
    contrast: 0.12,
    saturation: -0.05,
  }),
  preset("indoor-tungsten", "Indoor Tungsten", "Auto white balance losing the fight with lamps.", {
    grain: 0.44,
    jpeg: 0.36,
    colorShift: 0.62,
    vignette: 0.3,
    softness: 0.22,
    sharpen: 0.28,
    bloom: 0.24,
    aberration: 0.18,
    fade: 0.18,
    temperature: 0.62,
    exposure: -0.06,
    contrast: 0.1,
    saturation: 0.1,
  }),
  preset("camcorder-still", "Camcorder Still", "Frame grab look: soft, low detail, video colour.", {
    grain: 0.38,
    jpeg: 0.7,
    colorShift: 0.46,
    vignette: 0.24,
    softness: 0.5,
    sharpen: 0.24,
    bloom: 0.2,
    aberration: 0.3,
    fade: 0.34,
    temperature: 0.06,
    contrast: 0.06,
    saturation: 0.24,
  }),
  preset("beach-noon", "Beach Noon", "Overexposed daylight, hazy highlights, clipped sky.", {
    grain: 0.14,
    jpeg: 0.22,
    colorShift: 0.38,
    vignette: 0.1,
    softness: 0.12,
    sharpen: 0.4,
    bloom: 0.44,
    aberration: 0.24,
    fade: 0.22,
    temperature: 0.22,
    exposure: 0.24,
    contrast: 0.18,
    saturation: 0.22,
  }),
];

export const PRESET_MAP: Record<string, Preset> = Object.fromEntries(
  PRESETS.map((p) => [p.id, p]),
);

export function paramsEqual(a: EffectParams, b: EffectParams): boolean {
  return (Object.keys(a) as (keyof EffectParams)[]).every(
    (k) => Math.abs(a[k] - b[k]) < 0.0005,
  );
}
